global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mini-pc-system'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mini-pc-docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'raspberry-pi-system'
    static_configs:
      - targets: ['raspberrypi:9100']

  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole-exporter:9617']
