# yaml-language-server: $schema=https://raw.githubusercontent.com/kometa-team/kometa/nightly/json-schema/config-schema.json
## Do not remove the above line
## This file is a template remove the .template to use the file

## Plex and TMDb are the two connections which are required for the script to run

plex:                                                                    # Can be individually specified per library as well; REQUIRED for the script to run
  url: <<PLEXURL>>                                                       # Enter Plex URL (REQUIRED); this needs to point to your server, not app.plex.tv
  token: <<PLEXTOKEN>>                                                   # Enter Plex Token (REQUIRED)
  timeout: 60
  db_cache: 40
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: true
tmdb:
  apikey: <<TMDBAPIKEY>>                                                 # Enter TMDb API Key (REQUIRED)
  cache_expiration: 60
  language: en
  region:

                                   ## At least one library has to be configured for the script to do anything meaningful
libraries:
  German Movies:                                                         # These are names of libraries in your Plex
    remove_overlays: false                                               # Set this to true to remove all overlays
    collection_files: &id001
    - default: imdb                                                      # This is a file within Kometa's defaults folder
      template_variables:
        sort_prefix: :::01                                               # this will prefix collection names with "02 - " to help with sorting
    - default: tmdb
      template_variables:
        sort_prefix: :::02                                               # this will prefix collection names with "02 - " to help with sorting
    - default: oscars
      template_variables:
        sort_prefix: :::03

    overlay_files: &id002
    - default: ribbon
    - default: ratings                                                   # 5, 6, 7
      template_variables: &rating_vars
        rating1: critic                                                  # 5 as this is user and mass_user_rating_update: mdb_tomatoes
        rating1_image: imdb                                              # 5 as this is user and mass_user_rating_update: mdb_tomatoes

        rating2: audience                                                # 6 as this is critic and mass_critic_rating_update: imdb
        rating2_image: tmdb                                              # 6 as this is critic and mass_critic_rating_update: imdb

        rating3: user                                                    # 7 as this is audience and mass_audience_rating_update: tmdb
        rating3_image: rt_tomato                                         # 7 as this is audience and mass_audience_rating_update: tmdb

        horizontal_position: right                                       # the set of ratings is on the right of the poster

    operations: &op001
      mass_user_rating_update: mdb_tomatoes                              # 5 This operation will update the user rating in plex with Rotten Tomatoes ratings information gathered through mdblist.com (mdblist config required)
      mass_critic_rating_update: imdb                                    # 6 This operation will update the critic rating in plex with IMDb ratings information
      mass_audience_rating_update: tmdb                                  # 7 This operation will update the audience rating in plex with TMDb ratings information

  English Movies:                                                        # These are names of libraries in your Plex
    remove_overlays: false                                               # Set this to true to remove all overlays
    collection_files: *id001
    overlay_files: *id002
                                                                         # the set of ratings is on the right of the poster
    operations: *op001
                                                                         # 7 This operation will update the audience rating in plex with TMDb ratings information

  TV Shows:
    remove_overlays: false                                               # Set this to true to remove all overlays
    collection_files:
    - default: tmdb                                                      # This is a file within Kometa's defaults folder
    - default: imdb                                                      # This is a file within Kometa's defaults folder

    overlay_files:
    - default: ribbon
      level: show
    - default: ratings
      template_variables: *rating_vars
      level: show
    - default: ratings
      template_variables:
        <<: *rating_vars
        builder_level: episode
      level: episode

    operations:
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb

#  Anime:
#    collection_files:
#      - default: basic                                                  # This is a file within Kometa's defaults folder
#      - default: anilist                                                # This is a file within Kometa's defaults folder

playlist_files:
- default: playlist                                                      # This is a file within Kometa's defaults folder
  template_variables:
    libraries: Movies, TV Shows                                          # list of libraries that you want the Kometa Defaults playlists to look at

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory:
  - config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
#   run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_unfiltered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90

  run_again_delay: 0
webhooks:                                                                # Can be individually specified per library as well
  changes:
  delete:
  error:
  run_end:
  run_start:
  version:

# tautulli:                                                              # Can be individually specified per library as well
#   url: http://192.168.1.12:8181                                        # Enter Tautulli URL (Optional)
#   apikey:                                                              # Enter Tautulli API Key (Optional)
# github:
#   token:                                                               # Enter GitHub Personal Access Token (Optional)

omdb:
  apikey: <<OMDBAPIKEY>>                                                 # Enter OMDb API Key (Optional)
  cache_expiration: 60
mdblist:
  apikey: <<MDBLISTAPIKEY>>                                              # Enter MDBList API Key (Optional)
  cache_expiration: 60
# notifiarr:
#   apikey:                                                              # Enter Notifiarr API Key (Optional)
# gotify:
#   url: http://192.168.1.12:80                                          # Enter Gotify server URL (Optional)
#   token:                                                               # Enter Gotify Token (Optional)
# ntfy:
#   url: http://192.168.1.12:80                                          # Enter ntfy server URL (Optional)
#   token:                                                               # Enter ntfy Access Token (Optional)
#   topic:                                                               # Enter ntfy Topic (Optional)
# anidb:                                                                 # Not required for AniDB builders unless you want mature content
#   username:                                                            # Enter AniDB Username (Optional)
#   password:                                                            # Enter AniDB Password (Optional)
#   cache_expiration: 60
#   client:                                                              # Enter AniDB Client (Optional)
#   language: en
#   version: 1
# radarr:                                                                # Can be individually specified per library as well
#   url: http://192.168.1.12:7878                                        # Enter Radarr server URL (Optional)
#   token:                                                               # Enter Radarr API Key (Optional)
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: "S:/Movies"                                        # This value is CASE SENSITIVE
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p                                            # This value is CASE SENSITIVE
#   tag:
#   search: false
#   radarr_path:                                                         # This value is only needed in combination with the *_existing settings
#   plex_path:                                                           # This value is only needed in combination with the *_existing settings
#   ignore_cache: false
# sonarr:                                                                # Can be individually specified per library as well
#   url: http://192.168.1.12:8989                                        # Enter Sonarr server URL (Optional)
#   token:                                                               # Enter Sonarr API Key (Optional)
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: "S:/TV Shows"                                      # This value is CASE SENSITIVE
#   monitor: all
#   quality_profile: HD-1080p                                            # This value is CASE SENSITIVE
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:                                                         # This value is only needed in combination with the *_existing settings
#   plex_path:                                                           # This value is only needed in combination with the *_existing settings
#   ignore_cache: false
# trakt:
#   client_id:                                                           # Enter Trakt Client ID (Optional)
#   client_secret:                                                       # Enter Trakt Client Secret (Optional)
#   pin:
#   authorization:
#                                                                        # authorization section is autofilled by the script
#     access_token:
#     created_at:
#     expires_in:
#     refresh_token:
#     scope: public
#     token_type:
# mal:
#   client_id:                                                           # Enter MyAnimeList Client ID (Optional)
#   client_secret:                                                       # Enter MyAnimeList Client Secret (Optional)
#   cache_expiration: 60
#   localhost_url:
#   authorization:
#                                                                        # authorization section is autofilled by the script
#     access_token:
#     expires_in:
#     refresh_token:
#     token_type:
